#!/bin/sh

set -eu

[ "${DEBUG:-}" ] && set -x

PIDFILE=/app/monit/"$(basename $0)".pid

case "${1:-}" in
  start)
    exec /bin/sh -c '
      echo $$ >"$PIDFILE"
      echo "HELLO"
      ls -laRt /app/monit

      sleep 20
    ' &
    ;;

  stop)
    kill `cat "$PIDFILE"`
    rm -v "$PIDFILE"
    ;;
esac
