#!/bin/sh

set -eu

[ "${DEBUG:-}" ] && set -x

PIDFILE=/app/monit/"$(basename $0)".pid


case "${1:-}" in
  start)
    exec /bin/sh -c '
      echo $$ >"$PIDFILE"
      sleep 40

      ls -laRt /app/monit
      monit quit
    ' &
    ;;

  stop)
    kill `cat "$PIDFILE"`
    rm -v "$PIDFILE"
    ;;
esac
